STRAVA_CLIENT_ID = "181880"
STRAVA_CLIENT_SECRET = "de97f6aaf45dd77a07eebf0619f943c5dd76dcf5"
STRAVA_REDIRECT_URI="https://agentemindbody.streamlit.app/Connessioni_Fitness"
GEMINI_API_KEY = "AIzaSyC1j7K8pYwRCgvHGD4fQpWu0VSny6IosWE"
